- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    
- name: Allow docker-compose to be executed
  file:
    path: /usr/local/bin/docker-compose
    state: file
    mode: "+x"

- name: Create a symbolic link to docker-compose on /usr/bin
  file:
    path: /usr/bin/docker-compose
    src: /usr/local/bin/docker-compose
    state: link