---
- name: Get Docker installer script
  get_url: 
    url: https://get.docker.com
    dest: /tmp/get_docker.sh

- name: Allow Docker installer script to be executed
  file:
    path: /tmp/get_docker.sh
    state: file
    mode: "+x"

- name: Install Docker
  command: bash /tmp/get_docker.sh

- name: "Adding given user to docker group"
  user:
    name: "{{ user }}"
    groups: docker
    append: yes
